import re

SCAM_PATTERNS = {
    "urgency": [
        "act now", "urgent", "limited time", "immediately",
        "account will be closed", "last chance", "expire", "auth"
    ],
    "financial": [
        "upi", "bank", "wallet", "payment", "refund",
        "prize", "lottery", "cash", "money", "btc", "crypto"
    ],
    "impersonation": [
        "support team", "customer care", "official",
        "government", "income tax", "police", "irs", "fbi"
    ],
    "coercion": [
        "leak", "expose", "arrest", "court", "warrant",
        "footage", "recorded", "shame", "family"
    ],
    "links": [
        "http", "www", ".com", ".in", ".xyz", "bit.ly", "tinyurl"
    ]
}

def extract_triggers(text: str):
    text_lower = text.lower()
    triggers = []
    seen = set()

    for category, keywords in SCAM_PATTERNS.items():
        for kw in keywords:
            if kw in text_lower and kw not in seen:
                triggers.append((category, kw))
                seen.add(kw)

    return triggers

def build_text_summary(category, risk_score, confidence, text, toxic_score=0):
    triggers = extract_triggers(text)
    
    if category == "SAFE":
        return {
            "verdict": "This message appears safe.",
            "reason": "No aggressive, urgent, or scam-related patterns were detected.",
            "confidenceNote": f"{int(confidence * 100)}% confidence",
            "triggers": []
        }

    # Construct Dynamic Reason
    cats = list(set([t[0] for t in triggers]))
    reason_parts = []
    
    if "coercion" in cats or toxic_score > 0.7:
        reason_parts.append("coercive language designed to threaten or extort")
    if "urgency" in cats:
        reason_parts.append("urgency cues forcing immediate action")
    if "financial" in cats:
        reason_parts.append("financial pressure")
    if "impersonation" in cats:
        reason_parts.append("impersonation of authority")
    
    if not reason_parts:
        reason = "The AI detected suspicious structural patterns common in spam."
    else:
        reason = "This message uses " + ", ".join(reason_parts) + "."

    return {
        "verdict": "Potential Scam / Threat Detected",
        "reason": reason.capitalize(),
        "confidenceNote": f"{risk_score}% Risk Score",
        "triggers": [f"Detected {t[0]}: '{t[1]}'" for t in triggers[:5]]
    }

def build_image_summary(category, risk_score, confidence, features):
    if category == "REAL":
        return {
            "verdict": "This image appears authentic.",
            "reason": "Forensic analysis of pixel noise and compression artifacts found no signs of manipulation.",
            "confidenceNote": f"{int(confidence * 100)}% Safe",
            "triggers": []
        }
    elif category == "UNCERTAIN":
        return {
            "verdict": "Uncertain Content (Needs Review)",
            "reason": "Minor forensic anomalies were detected, but they may be due to high compression or studio lighting. Proceed with caution.",
            "confidenceNote": f"Score: {risk_score}/100",
            "triggers": features
        }
    
    return {
        "verdict": "Artificial / Manipulated Image Detected",
        "reason": "Facial texture inconsistencies and compression artifacts strongly suggest this image was generated by AI.",
        "confidenceNote": f"{risk_score}% Risk Score",
        "triggers": features
    }

def build_audio_summary(category, risk_score, confidence, features):
    if category == "REAL":
        return {
            "verdict": "This audio appears natural.",
            "reason": "The voice exhibits natural pitch fluctuations and environmental noise typical of real recordings.",
            "confidenceNote": f"{int(confidence * 100)}% Safe",
            "triggers": []
        }
    elif category == "UNCERTAIN":
        return {
            "verdict": "Uncertain Voice (Needs Review)",
            "reason": "The audio exhibits some synthetic characteristics, but they are not definitive. It could be due to low-quality recording or subtle processing.",
            "confidenceNote": f"Score: {risk_score}/100",
            "triggers": features
        }
        
    return {
        "verdict": "Synthetic / AI-Cloned Voice Detected",
        "reason": "The audio shows unnaturally stable pitch and lacks the micro-variations found in human speech.",
        "confidenceNote": f"{risk_score}% Risk Score",
        "triggers": features
    }

def build_video_summary(category, risk_score, confidence, features):
    if category == "REAL":
        return {
            "verdict": "This video appears authentic.",
            "reason": "Frame-to-frame analysis shows consistent lighting, motion, and natural blinking patterns.",
            "confidenceNote": f"{int(confidence * 100)}% Safe",
            "triggers": []
        }
    elif category == "UNCERTAIN":
        return {
            "verdict": "Uncertain Video (Needs Review)",
            "reason": "Subtle frame jitters or temporal inconsistencies were found, but not at a level to confirm manipulation. Could be due to vlog-style movement.",
            "confidenceNote": f"Score: {risk_score}/100",
            "triggers": features
        }
        
    return {
        "verdict": "Deepfake / Manipulated Video Detected",
        "reason": "Irregular blinking patterns and facial jitter between frames strongly suggest synthetic manipulation.",
        "confidenceNote": f"{risk_score}% Risk Score",
        "triggers": features
    }
